import { useState } from 'react';
import { ChevronLeft } from 'lucide-react';

const ABXS_SECTIONS = [
  { id: 'principles', title: 'Stewardship Principles', icon: '',
    items: [
      { term: 'The 5 D\'s of Antimicrobial Stewardship', def: 'Drug, Dose, Duration, De-escalation, Documentation. Start smart, then focus. Right drug: match spectrum to suspected pathogen. Right dose: weight-based, renal/hepatic-adjusted, TDM where applicable. Right duration: shortest effective course - CAP 5 days, cystitis 3-7 days, cellulitis 5 days. De-escalation: narrow from cultures at 48-72h. Documentation: indication, start date, planned stop/review date in chart.', detail: 'Biomarkers: Procalcitonin (PCT) >0.25 mcg/L suggests bacterial infection; guides de-escalation in respiratory infections and sepsis (ProREAL trial: reduces duration ~3 days). CRP: less specific but downtrend supports treatment adequacy. 1,3-beta-D-glucan: invasive fungal infection marker.', pearl: 'Antibiotic stewardship interventions that work: (1) Prospective audit with feedback - ID pharmacist/physician reviews and recommends at 48h. (2) Preauthorization for restricted agents (carbapenems, antifungals). (3) Automatic IV to oral conversion triggers. (4) Clinical decision support (CDS alerts). (5) Antibiogram - local resistance patterns guide empiric choices. (6) Allergy assessment and delabeling (10% of patients labeled penicillin-allergic; true allergy <1%).' },
      { term: 'Spectrum Matching & De-escalation', def: 'Community-acquired infections rarely need MRSA/Pseudomonas coverage. Hospital-acquired/ICU: broader initial spectrum justified, but NARROW within 48-72h when cultures return. IV-to-PO switch when clinically improving, tolerating oral, and bioavailable oral option available. High-bioavailability oral agents (>80%): fluoroquinolones, metronidazole, linezolid, fluconazole, clindamycin, doxycycline, TMP-SMX.', detail: 'Clinical switch criteria: afebrile x24h, HR <100, RR <24, tolerating PO, improving WBC. De-escalation examples: Vancomycin -> nafcillin/oxacillin (MSSA bacteremia - better outcomes with beta-lactam). Pip-Tazo -> ampicillin (Enterococcus UTI). Meropenem -> ceftriaxone (susceptible gram-negative). Vori -> fluconazole (susceptible Candida, improving patient). NEVER continue vancomycin if MSSA on cultures.', pearl: 'OPAT (Outpatient Parenteral Antibiotic Therapy): completion of IV courses at home. Requirements: reliable patient, home nursing, IV access, monitoring plan. OVIVA trial: oral antibiotics non-inferior to IV for bone/joint infections (osteomyelitis, septic arthritis, prosthetic joint). Dramatically changed practice - many infections previously requiring 6 weeks IV can be completed orally after initial improvement.' },
      { term: 'Duration of Therapy Evidence', def: 'Shorter is often equivalent or better. CAP: 5 days (not 10). Uncomplicated UTI: 3 days nitrofurantoin, single-dose fosfomycin. Cellulitis: 5 days. SSTI: 5-7 days. Bacteremia: S. aureus minimum 14 days from first negative blood culture (complicated: 4-6 weeks). Strep bacteremia 14 days. GNR bacteremia 7-14 days (MERINO). Sepsis without source: 7 days if responding.', detail: 'Defining "complicated" bacteremia (requiring longer treatment): endocarditis, device-related infection, osteomyelitis, metastatic foci, immunosuppression, persistent bacteremia >72h despite appropriate therapy. PET-CT increasingly used to find occult metastatic foci guiding duration. For S. aureus bacteremia: echocardiography (TTE then TEE if negative) mandatory to exclude endocarditis.', pearl: 'Stopping antibiotics early when cultures are negative: If blood cultures x48h negative in a non-immunocompromised patient without clear evidence of infection, consider stopping empiric antibiotics. "Culture-negative bacteremia" is uncommon - more often antibiotics were started for fever of non-infectious etiology. The PRORATA trial (procalcitonin-guided de-escalation in sepsis): PCT-guided de-escalation did NOT worsen day-28 mortality and reduced antibiotic exposure significantly.' },
      { term: 'Antibiotic Allergy Assessment', def: 'Penicillin allergy label on 10-15% of patients. True IgE-mediated allergy <1%. Cross-reactivity between penicillins and cephalosporins based on R1 side chain (not the beta-lactam ring) - overall cross-reactivity <2%. Patients with penicillin allergy label receive broader-spectrum antibiotics, have longer LOS, higher rates of C. diff, MRSA, and VRE infections.', detail: 'Risk stratification: Low risk (remote history of rash, no anaphylaxis) -> direct oral challenge (amoxicillin 250 mg test dose). Intermediate (urticaria, no anaphylaxis) -> skin testing or graded oral challenge. High risk (anaphylaxis, angioedema, SJS/TEN) -> allergy specialist referral. Penicillin skin testing: >95% negative predictive value for IgE-mediated allergy. Penicillin skin test negative -> amoxicillin oral challenge.', pearl: 'Cephalosporin cross-reactivity: amoxicillin/ampicillin share R1 side chain with cefadroxil, cefprozil, cephalexin - AVOID in true amoxicillin allergy. Ceftriaxone/cefotaxime have different R1 from penicillin - safe in most PCN-allergic patients. Aztreonam shares R1 side chain with ceftazidime only - can use aztreonam in cephalosporin-allergic patients (except ceftazidime-allergic). Carbapenems: <1% cross-reactivity with penicillin - can use in most PCN-allergic patients (except severe anaphylaxis).' },
    ]},
  { id: 'gram_pos', title: 'Gram-Positive Coverage', icon: '',
    items: [
      { term: 'MRSA: Current Antibiotic Options', def: 'Vancomycin: standard for serious MRSA. AUC/MIC-guided dosing (target AUC 400-600) per 2020 ASHP/IDSA/SIDP guidelines - not trough-based. Daptomycin: bactericidal, NOT for pneumonia (surfactant-inactivated), excellent for bacteremia/endocarditis/SSTI. Linezolid: bacteriostatic, excellent bioavailability (100%), penetrates bone/lung well - preferred for pneumonia, osteomyelitis. Ceftaroline: 5th-gen cephalosporin with MRSA activity, only cephalosporin active against MRSA.', detail: 'Newer anti-MRSA agents: Tedizolid (oxazolidinone, once daily, less myelosuppression). Oritavancin/Dalbavancin (long-acting lipoglycopeptides - single dose oritavancin or weekly dalbavancin for ABSSSI). Omadacycline (aminomethylcycline, oral/IV). Delafloxacin (fluoroquinolone active against MRSA - ABSSSI, CAP). Ceftaroline combinations with daptomycin: synergistic for daptomycin-non-susceptible MRSA.', pearl: 'Vancomycin failures: Consider daptomycin dose escalation (8-10 mg/kg), ceftaroline combo, or salvage with novel agents. MRSA bacteremia persistent after 72h despite vancomycin: ID consultation mandatory. Assess: adequate source control, metastatic foci (echo, MRI spine), adequate dosing (AUC monitoring), dialysis (removes vancomycin). Switch to daptomycin +/- beta-lactam if MIC creep or persistent bacteremia.' },
      { term: 'Clostridium Difficile (CDI)', def: 'Most common healthcare-associated infection. Toxin-producing C. difficile. Risk factors: antibiotics (clindamycin, fluoroquinolones, cephalosporins #1-3), hospitalization, PPI use, age >65, IBD. Diagnosis: NAAT (PCR - very sensitive, detects colonization), toxin EIA (specific for disease). Two-step recommended: NAAT positive -> toxin EIA positive = CDI. Treat only if symptomatic + positive test.', detail: 'Classification: Non-severe (WBC <15K, Cr <1.5x baseline), Severe (WBC >15K or Cr >1.5x baseline), Fulminant (ileus, megacolon, hypotension/shock). Treatment: Non-severe/severe: oral vancomycin 125mg QID x10 days (preferred over metronidazole since 2017 IDSA guidelines). Fidaxomicin 200mg BID x10 days: similar cure, lower recurrence especially non-NAP1 strains. Fulminant: vanco 500mg QID via NGT + rectal + IV metronidazole; surgical consult.', pearl: 'Recurrent CDI (25% after 1st, 65% after 2nd): options - extended/tapered vancomycin taper over 6 weeks, fidaxomicin, bezlotoxumab (anti-toxin B monoclonal antibody). FMT (fecal microbiota transplant): ~90% cure for recurrent CDI, FDA-approved products (Rebyota rectal enema, Vowst oral capsules). Infection control: C. diff spores RESIST alcohol hand sanitizer - SOAP AND WATER mandatory. Contact precautions + bleach-based surface disinfection (not quaternary ammonium compounds - ineffective against spores).' },
      { term: 'Beta-Lactam Spectrum Reference', def: 'Gen 1 cephalosporins (cefazolin): MSSA, E. coli, Klebsiella, Proteus - surgical prophylaxis, MSSA bacteremia. Gen 2 (cefoxitin): adds anaerobic coverage. Gen 3 (ceftriaxone): streptococci, H. flu, Neisseria, gram-negs (NOT Pseudomonas). Gen 4 (cefepime): adds Pseudomonas. Gen 5 (ceftaroline): adds MRSA. Anti-staph penicillins (nafcillin, oxacillin): MSSA - superior to vancomycin for MSSA bacteremia (lower mortality, faster clearance).', detail: 'Carbapenems: meropenem, imipenem, doripenem - broadest gram-neg spectrum (ESBL, AmpC, KPC-producing). Active against Pseudomonas (mero/imi/dori) but NOT MRSA or VRE. Ertapenem: no Pseudomonas/Acinetobacter - useful for ESBL step-down. Piperacillin-tazobactam (pip-tazo): gram-pos + gram-neg + anaerobes + Pseudomonas. Better than vancomycin + pip-tazo combo (CAMERA2 trial: combo increases nephrotoxicity without benefit). Amoxicillin-clavulanate: MSSA, H. flu, Moraxella, anaerobes - oral step-down for many infections.', pearl: 'ESKAPE organisms (highest antibiotic resistance burden): Enterococcus faecium (VRE), Staphylococcus aureus (MRSA), Klebsiella pneumoniae (ESBL/CRE), Acinetobacter baumannii (MDR/XDR), Pseudomonas aeruginosa (MDR), Enterobacter species (AmpC inducible). CRE (carbapenem-resistant Enterobacteriaceae): KPC -> ceftazidime-avibactam (CAZ-AVI). MBL (NDM, VIM, IMP) -> cefiderocol or aztreonam + CAZ-AVI. Acinetobacter XDR -> sulbactam-durlobactam (ATM-DUR), cefiderocol.' },
    ]},
  { id: 'specific_infections', title: 'Specific Infection Management', icon: '',
    items: [
      { term: 'Community-Acquired Pneumonia (CAP)', def: 'Outpatient low-risk (CURB-65 0-1 or PSI class I-II): amoxicillin 1g TID OR doxycycline 100mg BID OR azithromycin (if no resistance concerns). Outpatient high-risk: respiratory FQ (levofloxacin 750mg, moxifloxacin) OR beta-lactam + macrolide. Inpatient non-ICU: beta-lactam (ampicllin-sulbactam, ceftriaxone) + azithromycin OR respiratory FQ monotherapy. ICU: beta-lactam + azithromycin (preferred per guidelines, reduces mortality) OR beta-lactam + respiratory FQ.', detail: 'MRSA CAP (risk factors: recent MRSA infection/colonization, IVDU, structural lung disease): add vancomycin or linezolid. Pseudomonas CAP (risk factors: bronchiectasis, structural lung disease, prior Pseudomonas, recent broad-spectrum antibiotics, ICU admission): antipseudomonal beta-lactam + azithromycin/FQ. CAP duration: 5 days minimum; extend if no clinical improvement (consider non-infectious DDx). Legionella: test urinary antigen; treat with azithromycin or FQ (NOT beta-lactam alone).', pearl: 'HCAP (healthcare-associated pneumonia): previously a distinct category requiring broad-spectrum coverage. 2019 ATS/IDSA guidelines removed HCAP. Use CAP guidelines for most patients with healthcare exposure; only use broad-spectrum empirically if patient has risk factors for MDR organisms (prior resistant organism, known colonization) or LIVES in high-resistance facility. Over-broad coverage for HCAP label increased adverse effects without improving outcomes (IDSA 2019 guideline change).' },
      { term: 'Sepsis Antibiotic Management', def: 'Hour-1 bundle (Surviving Sepsis Campaign): lactate, blood cultures x2, broad-spectrum antibiotics within 1 hour of septic shock recognition, 30 mL/kg IV crystalloid, vasopressors if hypotension persists. Each hour delay in antibiotics in septic shock: 7-10% increase in mortality. Empiric: vancomycin + pip-tazo (most common) OR vancomycin + cefepime OR vancomycin + meropenem (if high MDR risk, immunocompromised).', detail: 'CRB (culture-results-based) de-escalation at 48-72h: (1) Discontinue vancomycin if blood cultures negative and no MRSA risk factors. (2) Narrow to organism-directed therapy. (3) Discontinue anti-Pseudomonas agent if Pseudomonas not isolated and patient improving. Source control: essential for sepsis - drain abscess, remove infected devices, debride infected tissue. Source control delays worsen outcomes (each hour delay: 2-4% mortality increase for intra-abdominal sources). Antifungal: add echinocandin if immunocompromised, prolonged ICU + broad antibiotics + TPN, Candida from multiple sterile sites.', pearl: 'Empiric double coverage for Pseudomonas: once-standard practice now largely unsupported by RCTs. MERINO trial: meropenem vs pip-tazo for gram-negative bacteremia (pip-tazo inferior for ESBL). No mortality benefit from adding aminoglycoside to beta-lactam for gram-neg bacteremia. Double coverage for serious Pseudomonas infections (endocarditis, meningitis, neutropenic fever) still practiced. Duration of sepsis antibiotics: aim for shortest effective course (7 days for most sepsis without source, guided by PCT if available).' },
      { term: 'Urinary Tract Infections', def: 'Uncomplicated cystitis (women): nitrofurantoin macrocrystals 100mg BID x5 days (NOT if GFR <30), TMP-SMX DS BID x3 days (if local resistance <20%), fosfomycin 3g single dose, pivmecillinam (Europe). Avoid fluoroquinolones (reserve for serious infections per FDA guidance). Complicated UTI/pyelonephritis: IV ceftriaxone 1g daily -> oral step-down per cultures; FQ if susceptible and no contraindications. Duration: uncomplicated pyelonephritis 5-7 days FQ or 14 days TMP-SMX.', detail: 'CAUTI (catheter-associated UTI): most common HAI. 80-90% of nosocomial UTIs from catheters. Diagnosis: >10^5 CFU/mL + symptoms + pyuria (not bacteriuria alone). Remove/replace catheter at time of treatment. Treat symptomatic CAUTI only - 7 days if rapid response, 10-14 days if delayed. Asymptomatic bacteriuria: treat ONLY in pregnancy (GBS, GNR any count; GBS -> PCN prophylaxis in labor) and pre-urologic procedure. NOT in elderly, diabetics, catheterized patients, post-renal transplant (without specific symptoms).', pearl: 'Recurrent UTI prevention in women (>3/year or >2 in 6 months): (1) Post-coital prophylaxis - TMP-SMX SS or nitrofurantoin 50-100mg within 2h of intercourse. (2) Low-dose nightly prophylaxis - nitrofurantoin 50-100mg or TMP-SMX SS QHS x6-12 months. (3) Topical vaginal estrogen (postmenopausal) - restores Lactobacillus flora, reduces recurrences 36-75%. (4) D-mannose - emerging evidence; may reduce recurrence. (5) Methenamine hippurate - urinary antiseptic, low-risk alternative to antibiotics for prevention. (6) Cranberry - modest benefit, less than antibiotics.' },
    ]},
  { id: 'resistant', title: 'Resistant Organisms', icon: '',
    items: [
      { term: 'CRE and MDR Gram-Negatives', def: 'CRE (Carbapenem-Resistant Enterobacteriaceae): KPC (most common in US, K. pneumoniae carbapenemase), MBL (NDM-1, VIM, IMP - common in India, SE Asia, spread globally), OXA-48 (Middle East, Europe). KPC treatment: ceftazidime-avibactam (CAZ-AVI) - first-line, active against KPC + OXA-48 but NOT MBL. Meropenem-vaborbactam (KPC only). Imipenem-relebactam (KPC + some ESBL).', detail: 'NDM/MBL treatment: cefiderocol (siderophore cephalosporin - active against all CRE including MBL, Acinetobacter baumannii, Pseudomonas XDR), aztreonam + ceftazidime-avibactam combination (ATM + AVI: AVI protects ATM from MBL hydrolysis = effective against NDM). Panresistant Acinetobacter baumannii: sulbactam-durlobactam (FDA approved), cefiderocol, or polymyxin B/colistin + rifampin/tigecycline. MDR Pseudomonas: ceftolozane-tazobactam (strong anti-Pseudomonas, good for AmpC/ESBL), meropenem-vaborbactam, imipenem-relebactam.', pearl: 'CRKP (carbapenem-resistant Klebsiella pneumoniae) bloodstream infections: mortality 40-60%. CAZ-AVI-based regimens associated with better outcomes than colistin-based. Combination therapy for KPC-KP: CAZ-AVI + meropenem (synergistic, prevents CAZ-AVI resistance emergence). Test for blaKPC resistance at 72h if not responding. CRAB (carbapenem-resistant Acinetobacter baumannii): WHO priority 1 critical pathogen. Contact precautions + dedicated equipment essential for hospital infection control.' },
      { term: 'Antifungal Therapy', def: 'Echinocandins (micafungin 100mg/d, caspofungin 70mg loading -> 50mg/d, anidulafungin 200mg -> 100mg/d): first-line for invasive candidiasis/candidemia. Candidemia treatment: echinocandin + remove CVC + ophthalmology exam + echo (if prolonged) + minimum 14 days from first negative blood culture. Step-down to fluconazole once improving + cultures negative + not C. glabrata/krusei + oral route.', detail: 'C. auris: emerging MDR yeast, resistant to fluconazole, often amphotericin B, sometimes echinocandins. Contact precautions essential (environmental persistence). Check susceptibility - echinocandin if susceptible. Aspergillus: voriconazole first-line (target trough 1-5 mcg/mL, toxicity if >5). Isavuconazole: non-inferior, less drug interactions, no QTc prolongation. Mucormycosis (Rhizopus, Mucor): liposomal amphotericin B 4-6 mg/kg/d + surgical debridement. Isavuconazole/posaconazole step-down. Break-through mucormycosis on voriconazole prophylaxis.', pearl: 'Antifungal prophylaxis indications: (1) Fluconazole: high-risk ICU surgical patients (pancreatitis, bowel perforation), allogenic HSCT pre-engraftment. (2) Posaconazole: AML/MDS induction chemo (NEJM 2007: reduced invasive fungal infections, mortality), HSCT with GVHD on immunosuppression. (3) Micafungin: allogenic HSCT (NEJM 2004). PCP (Pneumocystis jirovecii) prophylaxis: TMP-SMX DS daily or TID/week - for HIV with CD4 <200, lung transplant (lifetime), other transplants (3-12 months), high-dose steroids (>20mg prednisone >1 month).' },
    ]},
  { id: 'special_populations', title: 'Special Populations', icon: '',
    items: [
      { term: 'Febrile Neutropenia', def: 'Defined: temp >38.3 once OR >38.0 for 1h + ANC <500 (or <1000 expected to fall <500). Oncologic emergency - start antibiotics within 30-60 min. MASCC score (>21 = low risk): outpatient oral therapy candidate (ciprofloxacin + amoxicillin-clavulanate). High-risk (MASCC <21, ANC <100, anticipated neutropenia >7d, significant comorbidity, inpatient onset): IV anti-pseudomonal beta-lactam (pip-tazo, cefepime, or meropenem).', detail: 'Add vancomycin ONLY when: hemodynamic instability, MRSA risk, CVC infection/cellulitis, known MRSA colonization, severe mucositis (viridans strep risk). Add antifungal (echinocandin) if: fever persists >4-7 days of broad antibiotics, prior invasive fungal infection, high-risk prolonged neutropenia. Do NOT add antifungal/antiviral empirically at onset. Typhlitis (neutropenic enterocolitis): cecal inflammation, RLQ pain, fever, neutropenia. CT shows bowel wall thickening. Treat: bowel rest + broad antibiotics (pip-tazo or meropenem) + surgical consult.', pearl: 'Duration of antibiotics in febrile neutropenia: continue until ANC recovery (>500) or documented infection fully treated. If no source found and afebrile: continue until ANC >500. G-CSF (filgrastim 5 mcg/kg/d): shortens duration of neutropenia and febrile neutropenia; prophylaxis indicated when risk of FN >20% (most HSCT, dose-dense regimens for breast/lymphoma). Secondary prophylaxis after FN episode: G-CSF or dose reduction. Bacteremia in FN: gram-positive (viridans strep from mucositis with cytarabine - risk of severe alpha-strep syndrome/ARDS - add vancomycin) and gram-negative (30-40%).' },
      { term: 'Surgical Prophylaxis', def: 'Principles: narrow spectrum, adequate tissue levels at time of incision, shortest effective duration. Cefazolin 2g IV within 60 min before incision (3g if BMI >120 kg or weight >120 kg): covers skin flora (Staph, Strep) for most procedures. Cefoxitin or ampicllin-sulbactam: colorectal, biliary, gynecologic. Clindamycin + gentamicin OR vancomycin + gentamicin: beta-lactam allergy alternatives.', detail: 'Duration: single dose sufficient for most procedures. Continue only if: cardiac surgery (up to 48h), orthopedic implants (24-48h based on procedure). Re-dose intraoperatively: procedures >4h, major blood loss >1.5L (redose after 1500mL blood loss or per drug-specific intervals: cefazolin every 4h if ongoing). Vancomycin prophylaxis: ONLY if beta-lactam allergic or known MRSA colonization / high institutional MRSA rate. Routine vancomycin prophylaxis leads to VRE selection and is NOT standard. Start within 120 min for vancomycin (slow infusion required).', pearl: 'Endocarditis prophylaxis (2007 AHA guidelines, minimally changed since): indicated ONLY for: (1) Prosthetic heart valves. (2) Previous IE. (3) Congenital heart disease (unrepaired cyanotic, repaired with prosthetic within 6 months, repaired with residual defect). (4) Cardiac transplant with valvulopathy. Pre-dental procedure (gingival tissue manipulation): amoxicillin 2g PO 30-60 min before (clindamycin no longer recommended due to C. diff risk - use azithromycin 500mg instead if PCN-allergic). NOT indicated for GI/GU procedures, piercing, tattoos.' },
    ]},
];

function AntibioticStewardshipView() {
  const [activeId, setActiveId] = useState(null);
  const active = ABXS_SECTIONS.find(s => s.id === activeId);

  return (
    <div className="flex-1 min-h-0 flex flex-col">
      <div className="px-4 py-3 shrink-0" style={{ borderBottom: '1px solid var(--border)' }}>
        <h2 className="font-black text-xl flex items-center gap-2"> Antibiotic Stewardship</h2>
        <p className="text-xs opacity-40 mt-0.5">De-escalation, duration & resistance patterns</p>
      </div>
      <div className="flex-1 min-h-0 overflow-y-auto custom-scrollbar p-4 space-y-3">
        {active ? (
          <div className="space-y-4 animate-fade-in-up">
            <div className="flex items-center gap-3">
              <button onClick={() => setActiveId(null)} className="glass w-9 h-9 rounded-xl flex items-center justify-center"><ChevronLeft size={16} /></button>
              <h2 className="font-black">{active.icon} {active.title}</h2>
            </div>
            {active.items.map((item, i) => (
              <div key={i} className="glass rounded-2xl p-5 space-y-2" style={{ border: '1px solid var(--border)' }}>
                <h3 className="font-black" style={{ color: 'var(--accent)' }}>{item.term}</h3>
                <p className="text-sm opacity-80 leading-relaxed">{item.def}</p>
                {item.detail && <p className="text-xs opacity-50 leading-relaxed">{item.detail}</p>}
                {item.pearl && (
                  <div className="glass rounded-xl p-3 mt-2 flex items-start gap-2 text-xs" style={{ background: '#10b98108', border: '1px solid #10b98120', color: '#10b981' }}>
                    <span></span><span className="leading-relaxed">{item.pearl}</span>
                  </div>
                )}
              </div>
            ))}
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {ABXS_SECTIONS.map(s => (
              <button key={s.id} onClick={() => setActiveId(s.id)}
                className="glass rounded-2xl p-5 text-left transition-all card-hover"
                style={{ border: '1px solid var(--border)' }}>
                <div className="text-3xl mb-2">{s.icon}</div>
                <h3 className="font-black">{s.title}</h3>
                <p className="text-xs opacity-40 mt-1">{s.items.length} topics</p>
              </button>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

export default AntibioticStewardshipView;
