import {
  LayoutDashboard, GraduationCap, MessageSquare, Settings,
  Layers, CheckSquare, Activity, PenLine, ListChecks, CalendarDays,
  Target, Award, History, Brain, BarChart2, Bell, Calculator, MapPin,
  Swords, TrendingUp, Mic2, Zap, Bookmark, BookOpen, FlaskConical,
  Stethoscope, Pill, Clipboard, Heart, Flame, BookMarked, FileText,
  CheckCheck, BarChart, Bone, ShieldCheck, Siren, Eye, Baby, Droplets,
  Search, HeartPulse, Thermometer, Bug, Skull, Microscope, Apple,
  BrainCircuit, MessageCircle, Scissors, Palette,
} from 'lucide-react';

export const NAV_ITEMS = [
  { icon: LayoutDashboard, label: 'Home',  v: 'library',    dis: false },
  { icon: GraduationCap,   label: 'Study', v: 'study',      dis: false },
  { icon: MessageSquare,   label: 'Tutor', v: 'chat',        dis: false },
  { icon: Settings,        label: 'More',  v: '__more__',   dis: false },
];

export const MORE_ITEMS = [
  { icon: Layers,        label: 'Cards',         v: 'flashcards' },
  { icon: CheckSquare,   label: 'Exams',         v: 'exams' },
  { icon: Activity,      label: 'Cases',         v: 'cases' },
  { icon: PenLine,       label: 'Notes',         v: 'notes' },
  { icon: ListChecks,    label: 'Tasks',         v: 'tasks' },
  { icon: CalendarDays,  label: 'Calendar',      v: 'calendar' },
  { icon: Target,        label: 'Goals',         v: 'goals' },
  { icon: Award,         label: 'Achievements',  v: 'achievements' },
  { icon: History,       label: 'Timeline',      v: 'timeline' },
  { icon: Brain,         label: 'Graph',         v: 'knowledge' },
  { icon: BarChart2,     label: 'Analytics',     v: 'analytics' },
  { icon: Bell,          label: 'Reminders',     v: 'reminders' },
  { icon: Calculator,    label: 'Med Calc',      v: 'calculator' },
  { icon: MapPin,        label: 'Study Plan',    v: 'studyplan' },
  { icon: Swords,        label: 'Simulator',     v: 'simulator' },
  { icon: TrendingUp,    label: 'Progress',      v: 'progress' },
  { icon: Mic2,          label: 'Podcast',       v: 'podcast' },
  { icon: Zap,           label: 'Focus Mode',    v: 'focusmode' },
  { icon: Bookmark,      label: 'Annotations',   v: 'annotations' },
  { icon: BookOpen,      label: 'Glossary',      v: 'glossary' },
  { icon: FlaskConical,  label: 'Lab Ref',       v: 'labref' },
  { icon: Stethoscope,   label: 'DDx Builder',   v: 'ddx' },
  { icon: Brain,         label: 'Mnemonics',     v: 'mnemonics' },
  { icon: Pill,          label: 'Drug Check',    v: 'drugcheck' },
  { icon: Clipboard,     label: 'Rx Pad',        v: 'rxpad' },
  { icon: Heart,         label: 'Vitals',        v: 'vitals' },
  { icon: Flame,         label: 'Streak',        v: 'streak' },
  { icon: Pill,          label: 'Pharma Ref',    v: 'pharma' },
  { icon: BookMarked,    label: 'Guidelines',    v: 'guidelines' },
  { icon: FileText,      label: 'Handouts',      v: 'handouts' },
  { icon: CheckCheck,    label: 'Procedures',    v: 'procedures' },
  { icon: BarChart,      label: 'EBM Tools',     v: 'ebm' },
  { icon: Bone,          label: 'Anatomy',       v: 'anatomy' },
  { icon: ShieldCheck,   label: 'OSCE Prep',     v: 'osce' },
  { icon: Siren,         label: 'ECG Guide',     v: 'ecg' },
  { icon: Eye,           label: 'Radiology',     v: 'radiology' },
  { icon: Baby,          label: 'Peds Dosing',   v: 'pedsdosing' },
  { icon: Droplets,      label: 'Fluids',        v: 'fluids' },
  { icon: Search,        label: 'Vignette Quiz', v: 'imagequiz' },
  { icon: HeartPulse,    label: 'Critical Care', v: 'criticalcare' },
  { icon: Thermometer,   label: 'ABG Analysis',  v: 'abg' },
  { icon: Bug,           label: 'Infections',    v: 'infections' },
  { icon: Skull,         label: 'Toxicology',    v: 'toxicology' },
  { icon: Microscope,    label: 'Pathology',     v: 'pathology' },
  { icon: Bug,           label: 'Micro Guide',   v: 'microbiology' },
  { icon: Apple,         label: 'Nutrition',     v: 'nutrition' },
  { icon: BrainCircuit,  label: 'Psych Screen',  v: 'psychscreen' },
  { icon: BarChart,      label: 'Research',      v: 'research' },
  { icon: MessageCircle, label: 'Comm Skills',   v: 'commskills' },
  { icon: ListChecks,    label: 'Quality Improv', v: 'qi' },
  { icon: Baby,          label: 'OB/GYN Calc',   v: 'obgyn' },
  { icon: ShieldCheck,   label: 'Medical Ethics', v: 'ethics' },
  { icon: Scissors,      label: 'Surg Anatomy',  v: 'surganatomy' },
  { icon: Clipboard,     label: 'Wound Care',    v: 'woundcare' },
  { icon: Pill,          label: 'Pain Mgmt',     v: 'painmgmt' },
  { icon: Activity,      label: 'Geriatrics',    v: 'geriatrics' },
  { icon: Heart,         label: 'Palliative',    v: 'palliative' },
  { icon: Droplets,      label: 'Transfusion',   v: 'transfusion' },
  { icon: ShieldCheck,   label: 'Abx Steward',   v: 'abxsteward' },
  { icon: BarChart2,     label: 'Vent Graphs',   v: 'ventgraphs' },
  { icon: HeartPulse,    label: 'Hemodynamics',  v: 'hemodynamics' },
  { icon: Palette,       label: 'Dermatology',   v: 'dermatology' },
  { icon: Eye,           label: 'Ophthalmology', v: 'ophthalmology' },
  { icon: Droplets,      label: 'Nephrology',    v: 'nephrology' },
  { icon: Thermometer,   label: 'Endocrinology', v: 'endocrinology' },
  { icon: Activity,      label: 'Hematology',    v: 'hematology' },
  { icon: Bone,          label: 'Rheumatology',  v: 'rheumatology' },
  { icon: Brain,         label: 'Neurology',     v: 'neurology' },
  { icon: HeartPulse,    label: 'Cardiology',    v: 'cardiology' },
  { icon: Stethoscope,   label: 'Pulmonology',   v: 'pulmonology' },
  { icon: FlaskConical,  label: 'Gastroenterology', v: 'gastro' },
  { icon: Siren,         label: 'Emergency Med', v: 'emergency' },
  { icon: Bone,          label: 'Orthopedics',   v: 'orthopedics' },
  { icon: Mic2,          label: 'ENT',           v: 'ent' },
  { icon: Search,        label: 'Urology',       v: 'urology' },
  { icon: Settings,      label: 'Settings',      v: 'settings' },
];
